-- WezTerm Configuration
--
-- This file exists for editor LSP support and as the editable source of truth.
-- The actual config used at runtime is generated by the Nix module (wezterm.nix),
-- which reads this file and injects platform-specific Lua via lib.optionalString.
--
-- To apply changes: home-manager switch --flake .#default --impure

local wezterm = require('wezterm')
local config = wezterm.config_builder()

return config
