-- WezTerm Configuration
--
-- This file exists solely for editor/LSP support. Edits here have no runtime effect.
-- The actual config used at runtime is generated by the Nix module (wezterm.nix),
-- which injects platform-specific Lua via lib.optionalString.
--
-- To change WezTerm config, edit wezterm.nix and run:
--   home-manager switch --flake .#default --impure

local wezterm = require('wezterm')
local config = wezterm.config_builder()

return config
