// Type declarations for the virtual module generated by vite-plugin-seed-data.ts at build time.
// Per-entity Seed* types are defined in their entity files; this module re-exports them
// under the names callers import from "virtual:budget-seed-data".
declare module "virtual:budget-seed-data" {
  export type { SeedTransaction } from "./entities/transaction";
  export type { SeedBudgetOverride, SeedBudget } from "./entities/budget";
  export type { SeedBudgetPeriod } from "./entities/budget-period";
  export type { SeedRule } from "./entities/rule";
  export type { SeedNormalizationRule } from "./entities/normalization-rule";
  export type { SeedStatement } from "./entities/statement";
  export type { SeedStatementItem } from "./entities/statement-item";
  export type { SeedReconciliationNote } from "./entities/reconciliation-note";
  export type { SeedWeeklyAggregate } from "./entities/weekly-aggregate";

  export interface SeedData {
    readonly transactions: SeedTransaction[];
    readonly budgets: SeedBudget[];
    readonly budgetPeriods: SeedBudgetPeriod[];
    readonly rules: SeedRule[];
    readonly normalizationRules: SeedNormalizationRule[];
    readonly statements: SeedStatement[];
    readonly statementItems: SeedStatementItem[];
    readonly reconciliationNotes: SeedReconciliationNote[];
    readonly weeklyAggregates: SeedWeeklyAggregate[];
  }

  const seedData: SeedData;
  export default seedData;
}
