import type { Plugin } from "vite";

/** Serves /feed.xml during dev. Production feed.xml is generated by the prerender script. */
export function feedXmlPlugin(getXml: () => string): Plugin {
  return {
    name: "feed-xml",
    configureServer(server) {
      server.middlewares.use("/feed.xml", (_req, res) => {
        try {
          const xml = getXml();
          res.setHeader("Content-Type", "application/rss+xml; charset=utf-8");
          res.end(xml);
        } catch (err) {
          const message = err instanceof Error ? err.message : String(err);
          console.error("[feed-xml plugin]", message);
          res.writeHead(500, { "Content-Type": "text/plain" });
          res.end(`feed.xml generation failed: ${message}`);
        }
      });
    },
  };
}
