// Generated by scripts/sync-feed-urls.ts — do not edit manually.
export const ALLOWED_FEED_URLS: ReadonlySet<string> = new Set([
  "https://www.bastionland.com/feeds/posts/default",
  "https://newschoolrevolution.com/feed/",
  "https://www.prismaticwasteland.com/?format=rss",
]);
