#!/usr/bin/env node
// Project a disposition graph into one self-contained HTML page, and/or into
// the two harness-context projections named by session-context: `--rules
// <dir>` (one file per `tier: global` node) and `--ancestry <node id>
// --local <file>` (one node's ancestry, pinned by blob hash).
//
// Usage:
//   node packages/disposition/project.mjs [rootDir] [--input nodes.json] \
//     [--out browser/index.html] [--rules dir] [--ancestry nodeId --local file]
//
// Without --input the graph is read with readGraph(rootDir) from ./read.mjs.
// Each output is independent and only runs when its own flag is given. For
// --out, the graph is inlined verbatim into
// packages/disposition/browser-template.html; every projection decision
// lives in that template, so this script only reads, checks, and writes.

import { readFile, writeFile, mkdir, readdir, rm } from "node:fs/promises";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const MARKER = "<!--DG:GRAPH-->";

function parseArgs(argv) {
  const opts = { rootDir: null, input: null, out: null, rules: null, ancestry: null, local: null };
  const valueFlags = { "--input": "input", "--out": "out", "--rules": "rules", "--ancestry": "ancestry", "--local": "local" };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a in valueFlags) {
      const v = argv[++i];
      if (v === undefined) throw new Error(`${a} needs a value`);
      opts[valueFlags[a]] = v;
    } else if (a.startsWith("--")) {
      throw new Error(`unknown flag ${a}`);
    } else if (opts.rootDir === null) {
      opts.rootDir = a;
    } else {
      throw new Error(`unexpected argument ${a}`);
    }
  }
  if (opts.rootDir === null) opts.rootDir = ".";
  if ((opts.ancestry === null) !== (opts.local === null)) {
    throw new Error("--ancestry and --local must be given together");
  }
  return opts;
}

async function loadGraph(opts) {
  if (opts.input) return JSON.parse(await readFile(resolve(opts.input), "utf8"));
  const { readGraph } = await import("./read.mjs");
  return await readGraph(resolve(opts.rootDir));
}

// Fatal on anything the page cannot render around; a warning on a field the
// page reads but the reader did not supply, so a contract drift is visible.
function check(graph) {
  const warn = [];
  if (!graph || typeof graph !== "object") throw new Error("graph is not an object");
  if (!Array.isArray(graph.nodes)) throw new Error("graph.nodes is not an array");
  if (!graph.graphs || typeof graph.graphs !== "object") throw new Error("graph.graphs is not an object");
  if (graph.nodes.length === 0) throw new Error("graph.nodes is empty; nothing to project");

  const seen = new Set();
  const defines = new Map();
  for (const n of graph.nodes) {
    if (!n || typeof n.id !== "string" || !n.id) throw new Error("a node has no id");
    if (seen.has(n.id)) throw new Error(`duplicate node id ${n.id}`);
    seen.add(n.id);
    if (typeof n.question !== "string" || !n.question) warn.push(`${n.id}: no question`);
    if (!(n.graph in graph.graphs)) warn.push(`${n.id}: graph "${n.graph}" is not in graphs`);
    if (typeof n.rank !== "number" || !(n.rank > 0) || n.rank > 1) warn.push(`${n.id}: rank ${n.rank} is not in (0,1]`);
    if (!n.status) warn.push(`${n.id}: no status`);
    if (!Array.isArray(n.children)) warn.push(`${n.id}: children is not an array`);
    if (!Array.isArray(n.under)) warn.push(`${n.id}: under is not an array`);
    for (const t of n.defines || []) {
      const key = String(t).toLowerCase();
      if (defines.has(key)) warn.push(`term "${t}" defined by both ${defines.get(key)} and ${n.id}`);
      else defines.set(key, n.id);
    }
  }
  for (const n of graph.nodes) {
    for (const id of n.under || []) if (!seen.has(id)) warn.push(`${n.id}: under names unknown ${id}`);
    for (const id of n.children || []) if (!seen.has(id)) warn.push(`${n.id}: children names unknown ${id}`);
    for (const c of n.cites || []) if (!seen.has(c && c.id)) warn.push(`${n.id}: cites unknown ${c && c.id}`);
    if (n.ceiling && !seen.has(n.ceiling)) warn.push(`${n.id}: ceiling names unknown ${n.ceiling}`);
  }
  return warn;
}

const RULES_NOTICE = "Generated by packages/disposition/project.mjs --rules; do not edit.";

/**
 * Project every `tier: global` node into its own rule file under `dir`, one
 * file per node, named `<slug>.md`: a `# <question>` heading, the exact
 * notice line session-context's rules are read against, a blank line, then
 * the node's `## Answer` text verbatim (nothing from the rationale).
 *
 * This function owns `dir`: an existing file at a written slug is replaced
 * unconditionally (generated or hand-written -- either way it is now stale),
 * and afterward, every other `.md` file already in `dir` that carries
 * RULES_NOTICE but was not just written is deleted, because it can only be
 * this function's own output from a node that is no longer `tier: global`.
 * A file without the notice is never deleted: silence about hand-written
 * files is what lets this function own the directory safely.
 *
 * @param {{nodes: object[]}} graph
 * @param {string} dir
 * @returns {Promise<{dir: string, written: string[], deleted: string[]}>}
 */
export async function writeRules(graph, dir) {
  const target = resolve(dir);
  await mkdir(target, { recursive: true });

  const written = [];
  const keep = new Set();
  for (const node of graph.nodes) {
    if (node.tier !== "global") continue;
    if (!node.authority) {
      throw new Error(`--rules: global-tier node ${node.id} has no authority stamp to project`);
    }
    if (typeof node.answer !== "string" || node.answer.length === 0) {
      throw new Error(`--rules: global-tier node ${node.id} has no '## Answer' section to project`);
    }
    const fileName = `${node.slug}.md`;
    const filePath = join(target, fileName);
    const { class: cls, by, date } = node.authority;
    const notice = `> Projected from ${node.id} (${cls}, ${by}, ${date}). ${RULES_NOTICE} If this file conflicts with the graph on the disposition ref, the graph wins.`;
    const content = `# ${node.question}\n${notice}\n\n${node.answer}\n`;
    await mkdir(dirname(filePath), { recursive: true });
    await writeFile(filePath, content);
    written.push(filePath);
    keep.add(fileName);
  }

  const deleted = [];
  for (const entry of await readdir(target, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith(".md") || keep.has(entry.name)) continue;
    const filePath = join(target, entry.name);
    const text = await readFile(filePath, "utf8");
    if (text.includes(RULES_NOTICE)) {
      await rm(filePath);
      deleted.push(filePath);
    }
  }

  return { dir: target, written, deleted };
}

/**
 * Breadth-first walk of `nodeId` and its ancestors up every `under` edge to
 * the roots: the node itself first, then its parents, then their parents,
 * and so on, each id appearing exactly once, at the shallowest depth it is
 * reachable from (a multi-parent join does not duplicate a shared ancestor).
 * Ties within one depth break by id, for a deterministic order.
 *
 * @param {string} nodeId
 * @param {Map<string, {id: string, under?: string[]}>} nodesById
 * @returns {string[]} nodeId then its ancestors, nearest first
 */
function ancestorChain(nodeId, nodesById) {
  if (!nodesById.has(nodeId)) {
    throw new Error(`--ancestry: no node with id '${nodeId}'`);
  }
  const order = [];
  const visited = new Set([nodeId]);
  let frontier = [nodeId];
  while (frontier.length > 0) {
    frontier.sort();
    order.push(...frontier);
    const next = new Set();
    for (const id of frontier) {
      for (const parent of nodesById.get(id).under ?? []) {
        if (!visited.has(parent)) {
          visited.add(parent);
          next.add(parent);
        }
      }
    }
    frontier = [...next];
  }
  return order;
}

/**
 * Write the `CLAUDE.local.md`-shaped ancestry projection of one node: a
 * title, a notice line that pins the node and every ancestor (nearest first,
 * up every `under` chain to the roots, no duplicates) to its exact blob
 * hash, then one `## <question>` section per node in that same list giving
 * its id, its authority class (or "open question" when it has none), and
 * its `## Answer` text verbatim.
 *
 * A `tier: global` node is pinned like any other ancestor -- its hash still
 * lets a bite detect that a rule moved under it -- but gets no section of
 * its own: its question and answer are already projected as a rule, and
 * repeating them here would give the two projections a chance to read
 * differently once only one is regenerated.
 *
 * @param {{nodes: object[]}} graph
 * @param {string} nodeId
 * @param {string} file
 * @returns {Promise<{file: string, content: string}>}
 */
export async function writeAncestry(graph, nodeId, file) {
  const nodesById = new Map(graph.nodes.map((n) => [n.id, n]));
  const chain = ancestorChain(nodeId, nodesById);

  const pins = chain.map((id) => `${id}@${nodesById.get(id).hash}`).join(", ");
  const lines = [
    `# Ancestry of ${nodeId}`,
    `> Projected by packages/disposition/project.mjs --ancestry; do not edit. Pins: ${pins} for the node and each ancestor.`,
    "",
  ];

  for (const id of chain) {
    const node = nodesById.get(id);
    if (node.tier === "global") continue;
    lines.push(`## ${node.question}`, "", `${node.id} (${node.authority ? node.authority.class : "open question"})`);
    if (typeof node.answer === "string" && node.answer.length > 0) {
      lines.push("", node.answer);
    }
    lines.push("");
  }
  while (lines.length > 0 && lines[lines.length - 1] === "") lines.pop();

  const content = `${lines.join("\n")}\n`;
  const filePath = resolve(file);
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, content);
  return { file: filePath, content };
}

export function build(template, graph) {
  if (!template.includes(MARKER)) throw new Error(`template has no ${MARKER} marker`);
  // "<" only ever occurs inside a JSON string, so escaping it keeps the
  // payload valid JSON and keeps "</script" out of the document.
  const json = JSON.stringify(graph).replace(/</g, "\\u003c");
  const block = `<script type="application/json" id="graph">${json}</script>`;
  return template.replace(MARKER, () => block);
}

// Builds the browser page only when opts.out is given -- --rules and
// --ancestry are independent outputs that do not need it (see writeRules,
// writeAncestry), and check() only makes sense against the page's contract.
export async function project(opts) {
  const graph = await loadGraph(opts);
  if (!opts.out) return { out: null, html: null, graph, warnings: [] };
  const warnings = check(graph);
  const template = await readFile(resolve(HERE, "browser-template.html"), "utf8");
  const html = build(template, graph);
  const out = resolve(opts.out);
  await mkdir(dirname(out), { recursive: true });
  await writeFile(out, html);
  return { out, html, graph, warnings };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  const opts = parseArgs(process.argv.slice(2));
  const { out, html, graph, warnings } = await project(opts);

  if (opts.rules) {
    const result = await writeRules(graph, opts.rules);
    for (const f of result.written) process.stdout.write(`wrote ${f}\n`);
    for (const f of result.deleted) process.stdout.write(`deleted ${f}\n`);
  }

  if (opts.ancestry) {
    const result = await writeAncestry(graph, opts.ancestry, opts.local);
    process.stdout.write(`wrote ${result.file}\n`);
  }

  if (out) {
    for (const w of warnings) process.stderr.write(`contract: ${w}\n`);
    process.stdout.write(
      `${graph.nodes.length} nodes, ${Object.keys(graph.graphs).length} graphs -> ${out} (${Buffer.byteLength(html)} bytes)\n`
    );
  }

  if (!out && !opts.rules && !opts.ancestry) {
    process.stderr.write("nothing to do: pass --out, --rules, or --ancestry (with --local)\n");
    process.exitCode = 1;
  }
}
