#!/usr/bin/env node
// Project a disposition graph into one self-contained HTML page, and/or into
// the harness-context projections named by session-context: `--rules <dir>`
// (one file per `tier: global` node), `--ancestry <node id> --local <file>`
// (one node's ancestry, pinned by blob hash), `--frontier <file>` (every
// node in rank order, `-` for stdout) -- the un-aligned-dispositions listing
// the browser itself excludes -- and `--alignment <file>` (`-` for stdout):
// the open dialogue the author rules on, one page, every node carrying a
// `stage`.
//
// Usage:
//   node packages/disposition/project.mjs [rootDir] [--input nodes.json] \
//     [--out browser/index.html] [--rules dir] [--ancestry nodeId --local file] \
//     [--frontier file] [--alignment file]
//
// Without --input the graph is read with readGraph(rootDir) from ./read.mjs.
// Each output is independent and only runs when its own flag is given. For
// --out, the graph is inlined verbatim into
// packages/disposition/browser-template.html; every projection decision
// lives in that template, so this script only reads, checks, and writes.

import { readFile, writeFile, mkdir, readdir, rm } from "node:fs/promises";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const MARKER = "<!--DG:GRAPH-->";

function parseArgs(argv) {
  const opts = { rootDir: null, input: null, out: null, rules: null, ancestry: null, local: null, frontier: null, alignment: null };
  const valueFlags = { "--input": "input", "--out": "out", "--rules": "rules", "--ancestry": "ancestry", "--local": "local", "--frontier": "frontier", "--alignment": "alignment" };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a in valueFlags) {
      const v = argv[++i];
      if (v === undefined) throw new Error(`${a} needs a value`);
      opts[valueFlags[a]] = v;
    } else if (a.startsWith("--")) {
      throw new Error(`unknown flag ${a}`);
    } else if (opts.rootDir === null) {
      opts.rootDir = a;
    } else {
      throw new Error(`unexpected argument ${a}`);
    }
  }
  if (opts.rootDir === null) opts.rootDir = ".";
  if ((opts.ancestry === null) !== (opts.local === null)) {
    throw new Error("--ancestry and --local must be given together");
  }
  return opts;
}

async function loadGraph(opts) {
  if (opts.input) return JSON.parse(await readFile(resolve(opts.input), "utf8"));
  const { readGraph } = await import("./read.mjs");
  return await readGraph(resolve(opts.rootDir));
}

// Fatal on anything the page cannot render around; a warning on a field the
// page reads but the reader did not supply, so a contract drift is visible.
function check(graph) {
  const warn = [];
  if (!graph || typeof graph !== "object") throw new Error("graph is not an object");
  if (!Array.isArray(graph.nodes)) throw new Error("graph.nodes is not an array");
  if (!graph.graphs || typeof graph.graphs !== "object") throw new Error("graph.graphs is not an object");
  if (graph.nodes.length === 0) throw new Error("graph.nodes is empty; nothing to project");

  const seen = new Set();
  const defines = new Map();
  for (const n of graph.nodes) {
    if (!n || typeof n.id !== "string" || !n.id) throw new Error("a node has no id");
    if (seen.has(n.id)) throw new Error(`duplicate node id ${n.id}`);
    seen.add(n.id);
    if (typeof n.question !== "string" || !n.question) warn.push(`${n.id}: no question`);
    if (!(n.graph in graph.graphs)) warn.push(`${n.id}: graph "${n.graph}" is not in graphs`);
    if (typeof n.rank !== "number" || !(n.rank > 0) || n.rank > 1) warn.push(`${n.id}: rank ${n.rank} is not in (0,1]`);
    if (!n.status) warn.push(`${n.id}: no status`);
    if (!Array.isArray(n.children)) warn.push(`${n.id}: children is not an array`);
    if (!Array.isArray(n.under)) warn.push(`${n.id}: under is not an array`);
    for (const t of n.defines || []) {
      const key = String(t).toLowerCase();
      if (defines.has(key)) warn.push(`term "${t}" defined by both ${defines.get(key)} and ${n.id}`);
      else defines.set(key, n.id);
    }
  }
  for (const n of graph.nodes) {
    for (const id of n.under || []) if (!seen.has(id)) warn.push(`${n.id}: under names unknown ${id}`);
    for (const id of n.children || []) if (!seen.has(id)) warn.push(`${n.id}: children names unknown ${id}`);
    for (const c of n.cites || []) if (!seen.has(c && c.id)) warn.push(`${n.id}: cites unknown ${c && c.id}`);
    if (n.ceiling && !seen.has(n.ceiling)) warn.push(`${n.id}: ceiling names unknown ${n.ceiling}`);
  }
  return warn;
}

const RULES_NOTICE = "Generated by packages/disposition/project.mjs --rules; do not edit.";

/**
 * Project every `tier: global` node into its own rule file under `dir`, one
 * file per node, named `<slug>.md`: a `# <question>` heading, the exact
 * notice line session-context's rules are read against, a blank line, then
 * the node's `## Answer` text verbatim (nothing from the rationale).
 *
 * This function owns `dir`: an existing file at a written slug is replaced
 * unconditionally (generated or hand-written -- either way it is now stale),
 * and afterward, every other `.md` file already in `dir` that carries
 * RULES_NOTICE but was not just written is deleted, because it can only be
 * this function's own output from a node that is no longer `tier: global`.
 * A file without the notice is never deleted: silence about hand-written
 * files is what lets this function own the directory safely.
 *
 * @param {{nodes: object[]}} graph
 * @param {string} dir
 * @returns {Promise<{dir: string, written: string[], deleted: string[]}>}
 */
export async function writeRules(graph, dir) {
  const target = resolve(dir);
  await mkdir(target, { recursive: true });

  const written = [];
  const keep = new Set();
  for (const node of graph.nodes) {
    if (node.tier !== "global") continue;
    if (!node.authority) {
      throw new Error(`--rules: global-tier node ${node.id} has no authority stamp to project`);
    }
    if (typeof node.answer !== "string" || node.answer.length === 0) {
      throw new Error(`--rules: global-tier node ${node.id} has no '## Answer' section to project`);
    }
    const fileName = `${node.slug}.md`;
    const filePath = join(target, fileName);
    const { class: cls, by, date } = node.authority;
    const stamp = node.stage ? `${node.status}: ${cls}, ${by}, ${date}; stage ${node.stage}` : `${node.status}: ${cls}, ${by}, ${date}`;
    const notice = `> Projected from ${node.id} (${stamp}). ${RULES_NOTICE} If this file conflicts with the graph on the disposition ref, the graph wins.`;
    const content = `# ${node.question}\n${notice}\n\n${node.answer}\n`;
    await mkdir(dirname(filePath), { recursive: true });
    await writeFile(filePath, content);
    written.push(filePath);
    keep.add(fileName);
  }

  const deleted = [];
  for (const entry of await readdir(target, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith(".md") || keep.has(entry.name)) continue;
    const filePath = join(target, entry.name);
    const text = await readFile(filePath, "utf8");
    if (text.includes(RULES_NOTICE)) {
      await rm(filePath);
      deleted.push(filePath);
    }
  }

  return { dir: target, written, deleted };
}

/**
 * Breadth-first walk of `nodeId` and its ancestors up every `under` edge to
 * the roots: the node itself first, then its parents, then their parents,
 * and so on, each id appearing exactly once, at the shallowest depth it is
 * reachable from (a multi-parent join does not duplicate a shared ancestor).
 * Ties within one depth break by id, for a deterministic order.
 *
 * @param {string} nodeId
 * @param {Map<string, {id: string, under?: string[]}>} nodesById
 * @returns {string[]} nodeId then its ancestors, nearest first
 */
function ancestorChain(nodeId, nodesById) {
  if (!nodesById.has(nodeId)) {
    throw new Error(`--ancestry: no node with id '${nodeId}'`);
  }
  const order = [];
  const visited = new Set([nodeId]);
  let frontier = [nodeId];
  while (frontier.length > 0) {
    frontier.sort();
    order.push(...frontier);
    const next = new Set();
    for (const id of frontier) {
      for (const parent of nodesById.get(id).under ?? []) {
        if (!visited.has(parent)) {
          visited.add(parent);
          next.add(parent);
        }
      }
    }
    frontier = [...next];
  }
  return order;
}

/**
 * Write the `CLAUDE.local.md`-shaped ancestry projection of one node: a
 * title, a notice line that pins the node and every ancestor (nearest first,
 * up every `under` chain to the roots, no duplicates) to its exact blob
 * hash, then one `## <question>` section per node in that same list giving
 * its id, its authority class (or, with no stamp, "proposal" when it has an
 * `## Answer` and "un-aligned" when it does not), and its `## Answer` text
 * verbatim.
 *
 * A `tier: global` node is pinned like any other ancestor -- its hash still
 * lets a bite detect that a rule moved under it -- but gets no section of
 * its own: its question and answer are already projected as a rule, and
 * repeating them here would give the two projections a chance to read
 * differently once only one is regenerated.
 *
 * @param {{nodes: object[]}} graph
 * @param {string} nodeId
 * @param {string} file
 * @returns {Promise<{file: string, content: string}>}
 */
export async function writeAncestry(graph, nodeId, file) {
  const nodesById = new Map(graph.nodes.map((n) => [n.id, n]));
  const chain = ancestorChain(nodeId, nodesById);

  const pins = chain.map((id) => `${id}@${nodesById.get(id).hash}`).join(", ");
  const lines = [
    `# Ancestry of ${nodeId}`,
    `> Projected by packages/disposition/project.mjs --ancestry; do not edit. Pins: ${pins} for the node and each ancestor.`,
    "",
  ];

  for (const id of chain) {
    const node = nodesById.get(id);
    if (node.tier === "global") continue;
    // The stamp's class when there is one (ratified/delegated/deferred --
    // unaffected by the answered/unanswered status split, which collapses
    // deferred into "unanswered" but is not what this label shows); with no
    // stamp, "unstamped" when the node at least has an answer to be a draft
    // of, and "un-aligned" (the disposition with a question and no answer
    // yet) when it does not. Inlined rather than importing deriveStatus:
    // this file is sometimes copied standalone (see project.test.mjs's
    // space-in-path CLI test), so it must not pick up a static
    // sibling-module dependency.
    const hasAnswer = typeof node.answer === "string" && node.answer.length > 0;
    const label = node.authority ? node.authority.class : hasAnswer ? "unstamped" : "un-aligned";
    lines.push(`## ${node.question}`, "", `${node.id} (${label})`);
    if (typeof node.answer === "string" && node.answer.length > 0) {
      lines.push("", node.answer);
    }
    lines.push("");
  }
  while (lines.length > 0 && lines[lines.length - 1] === "") lines.pop();

  const content = `${lines.join("\n")}\n`;
  const filePath = resolve(file);
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, content);
  return { file: filePath, content };
}

/**
 * Drop every node with no `## Answer` (`node.answer == null`) -- an
 * un-aligned disposition that has not survived the alignment dialogue --
 * from the data the browser receives: it renders no page, appears in no
 * nav tree or search, and defines no term, simply by being absent from
 * `nodes`. This is no longer a `status` check: `status` is now derived
 * from the stamp alone (see `deriveStatus`) and an unanswered node with an
 * answer -- a deferred or unstamped draft -- is very much shown, just
 * marked unanswered; only a genuine no-answer node is excluded here. Any
 * surviving node's `cites` entries and `children` list that point at a
 * dropped id are removed too, since the cited/child node no longer exists
 * in this projection; nothing else about a node changes. A graph with
 * nothing to drop is returned unchanged, and a node that names no dropped
 * id in either field is returned unchanged as well.
 *
 * This runs after `check()`, not before: `check()` validates the reader's
 * full contract, and a citation or child reference into a node this
 * function is about to drop is not a contract violation.
 *
 * @param {{nodes: object[]}} graph
 * @returns {{nodes: object[]}}
 */
export function excludeUnaligned(graph) {
  const dropped = new Set(graph.nodes.filter((n) => n.answer == null).map((n) => n.id));
  if (dropped.size === 0) return graph;
  const nodes = graph.nodes
    .filter((n) => !dropped.has(n.id))
    .map((n) => {
      const citesHit = (n.cites || []).some((c) => dropped.has(c.id));
      const childrenHit = (n.children || []).some((id) => dropped.has(id));
      if (!citesHit && !childrenHit) return n;
      const next = { ...n };
      if (citesHit) next.cites = n.cites.filter((c) => !dropped.has(c.id));
      if (childrenHit) next.children = n.children.filter((id) => !dropped.has(id));
      return next;
    });
  return { ...graph, nodes };
}

export function build(template, graph) {
  if (!template.includes(MARKER)) throw new Error(`template has no ${MARKER} marker`);
  // "<" only ever occurs inside a JSON string, so escaping it keeps the
  // payload valid JSON and keeps "</script" out of the document.
  const json = JSON.stringify(graph).replace(/</g, "\\u003c");
  const block = `<script type="application/json" id="graph">${json}</script>`;
  return template.replace(MARKER, () => block);
}

// `<id>` for a bare depends entry, `<id>#<alternative>` for a qualified
// one -- the same syntax `readDependsList` (read.mjs) parses back apart.
function formatDependsEntry(d) {
  return d.alternative ? `${d.id}#${d.alternative}` : d.id;
}

// The parenthetical breakdown shared by the ruling-order line and the
// per-node "settles:" detail line below, which differ only in the label's
// punctuation (inline prose there, a "key: value" detail line here).
function settlesBreakdown(node) {
  const s = node.settledBy;
  const alt = s.alternatives > 0 ? `; ${s.alternatives} alternatives, uncounted` : "";
  return `${node.settles} (${s.under} under, ${s.depends} depends${alt})`;
}

/**
 * Render every node in the graph as a flat markdown listing: first the
 * ruling order -- the alignment frontier (every node carrying a `stage`)
 * ranked by `settles` descending, then `rank` descending, then id, the
 * order in which a ruling settles the most still-open ground first -- then
 * every node in the graph, descending by `rank` alone (ties broken by id),
 * which is the frontier of un-aligned dispositions (and everything else)
 * that `excludeUnaligned` hides from the browser. Pure and deterministic:
 * nothing but the graph's own data, no dates or timestamps.
 *
 * @param {{module: string, nodes: object[]}} graph
 * @returns {string} markdown, newline-terminated
 */
export function renderFrontier(graph) {
  const nodes = [...graph.nodes].sort((a, b) => {
    if (b.rank !== a.rank) return b.rank - a.rank;
    return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
  });

  const rulingOrder = graph.nodes.filter((n) => n.stage).sort((a, b) => {
    if (b.settles !== a.settles) return b.settles - a.settles;
    if (b.rank !== a.rank) return b.rank - a.rank;
    return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
  });

  const lines = [`# Frontier of ${graph.module}`, "", "## Ruling order", ""];
  if (rulingOrder.length === 0) {
    lines.push("_none_");
  } else {
    rulingOrder.forEach((node, i) => {
      lines.push(`${i + 1}. ${node.id} — settles ${settlesBreakdown(node)} — rank ${node.rank.toFixed(4)} — stage ${node.stage}`);
    });
  }
  lines.push("", "## Every node, by rank", "");

  for (const node of nodes) {
    const head = [
      node.id,
      node.status,
      node.authority ? `${node.authority.class} (${node.authority.by}, ${node.authority.date})` : "no stamp",
      `rank ${node.rank.toFixed(4)}`,
    ];
    if (node.tier === "global") head.push("tier global");
    if (node.boost != null) head.push(`boost ${node.boost}`);
    lines.push(`- ${head.join(" — ")}`);

    if (node.order && node.order.length > 0) {
      const stepsText = node.order.map((step) => step.join(" = ")).join(" > ");
      lines.push(`  order: ${stepsText}`);
    }
    const hasAlternatives = node.alternatives && node.alternatives.length > 0;
    const hasDepends = node.depends && node.depends.length > 0;
    const dependsLine = () => {
      lines.push(`  depends: ${node.depends.map(formatDependsEntry).join(", ")}`);
    };
    if (node.stage) {
      lines.push(`  stage: ${node.stage}`);
      lines.push(`  settles: ${settlesBreakdown(node)}`);
      if (hasDepends && !hasAlternatives) dependsLine();
    }
    if (node.recommendation) {
      const rec = node.recommendation;
      const stale = node.recommendationStale ? ", standing text changed since the recommendation" : "";
      lines.push(`  recommendation: adopts ${rec.adopts}, boldness ${rec.boldness}${stale}`);
    }
    if ((node.facts || []).length > 0) {
      const facts = node.facts.map((f) => {
        const ruled = f.ruling ? `, ruled ${f.ruling.response} on ${f.ruling.choice} ${f.ruling.date}` : "";
        return `${f.name}: ${f.adopts} of ${f.choices.join("|")} (boldness ${f.boldness}${ruled})`;
      });
      lines.push(`  facts: ${facts.join("; ")}`);
    }
    if (node.review) {
      const stale = node.reviewStale ? ", draft changed since the review" : "";
      lines.push(`  review: ${node.review.verdict} (${node.review.strength}, ${node.review.date})${stale}`);
    }
    if (node.draft) lines.push("  draft: yes");
    if (hasAlternatives) {
      const named = node.alternatives.map((a) => `${a.name}:${a.source}`).join(", ");
      lines.push(`  alternatives: ${node.alternatives.length} (${named})`);
      if (hasDepends) dependsLine();
    }
    if (node.answer == null) lines.push(`  under: ${(node.under || []).join(", ")}`);
    if (node.instrument) {
      const note = node.instrument.note ? ` — ${node.instrument.note}` : "";
      lines.push(`  instrument: ${node.instrument.kind}: ${node.instrument.ref}${note}`);
    } else {
      lines.push("  instrument: none");
    }
    for (const s of node.shims || []) {
      lines.push(`  shim (${s.declared}): ${s.artifact} — for: ${s.for || "unstated"} — liquidation: ${s.liquidation}`);
    }
  }
  return `${lines.join("\n")}\n`;
}

/* ------------------------------------------------------------------ *
 * the alignment page: every node carrying a `stage` -- an unanswered
 * node, or an answered node whose ratification is under review -- rendered
 * as one flat, at-rest page the author rules on, in one ruling order
 * across every graph the manifest names (see `orderAlignmentItems`): a
 * graph is a label on each item, never a precedence, since the frontier's
 * dependencies cross graphs. Unlike the browser, every item is rendered to
 * HTML here, in Node, at build time: there is no per-node route to click
 * through, so the file itself already holds everything a reader (or a
 * test) will ever see, the edit between the node and its draft included.
 * alignment-template.html's own <script> is untouched by this function; it
 * only carries what has to run in a browser -- the theme toggle, staging
 * the author's responses, submitting them, and the "copy all" digest.
 * ------------------------------------------------------------------ */

const ALIGNMENT_MARKER = "<!--DG:ITEMS-->";

// The three responses the unanswered node opens on any subset of the
// items: the value stored on the response document, the button's label,
// and the label the textarea takes once that response is chosen.
const RESPONSE_CHOICES = [
  { value: "confirm", label: "Confirm", note: "A note (optional)" },
  { value: "edit", label: "Confirm with edits", note: "Your edits" },
  { value: "deny", label: "Deny with feedback", note: "Your feedback" },
];

// What each stage owes the author, said once beneath the item's account.
// A ruling-stage item's caption is the edit's own, right under the diff.
const STAGE_HINT = {
  review: "In review. A confirmation given now is held until the review forwards the draft.",
  periagogic: "The dialogue owes your account of the ground first; your words here are recorded verbatim.",
  maieutic: "The answer is not yet drafted; confirming takes the proposal's recommendation.",
  ruling: null,
};


const NO_ANSWER_LINE = "No answer yet: this node is the author's disposition awaiting its answer.";
const ADOPTED_MARK = "the recommendation adopts this";
const STANDING_CHOICE = "standing";
const REJECT_CHOICE = "__reject";
const REJECT_LABEL = "Reject all of these, with feedback";
const DECISION_NOTE_PLACEHOLDER = "Why, or what instead";
const DECISIONS_LBL = "What this ruling asks";
const NOTHING_ASKED = "Nothing on this node is asked separately: every decision on it folded in at low boldness. The ruling is the node as a whole.";
const FOLDED_LEAD = "Folded in, low boldness:";
const PANE_LBL = "The node as it would stand";
const INDICATIONS_LBL = "What a ruling here makes decidable";
const INDICATIONS_HINT = "Context, not rows: each is a node of its own and is ruled from the rail in its own turn in the order.";

/* The authority the text already in the record actually has, which is what
 * the choice keeping it must be named for. `authority` on a node is its
 * stamp, and a deferred stamp is not an answer: "until the author rules, a
 * deferred answer is unanswered". Testing the stamp's presence rather than
 * its class called every draft in the record "standing" -- on 2026-09-04 no
 * node of the 72 was ratified and 46 carried a deferred stamp -- and offered
 * a confirmation of the AI's own draft as the safe, ordinary choice
 * (commons.systems/disposition-graph/alignment-page, the author's finding on
 * commons.systems/public/agency). */
function standingState(n) {
  const hasAnswer = typeof n.answer === "string" && n.answer.length > 0;
  if (!hasAnswer) return "none";
  return n.authority && n.authority.class === "ratified" ? "ratified" : "draft";
}

const KEEP_LABELS = {
  ratified: "keep the answer as ratified",
  draft: "keep the AI's draft as it is",
  none: "leave the question open",
};
const KEEP_PILLS = {
  ratified: "ratified",
  draft: "unconfirmed",
  none: "nothing stands here",
};

/* What a confirmation of the whole would do, said on the control that would
 * do it. It reports the alternatives pending rather than asserting there are
 * none: the caption used to end "Nothing else is proposed" from the far side
 * of the screen while the decisions column proposed up to five, which was
 * false on 27 of the 72 nodes. */
function wholeCaption(n) {
  const state = standingState(n);
  const alts = Array.isArray(n.alternatives) ? n.alternatives.length : 0;
  const tail = alts === 0
    ? " Nothing else is proposed."
    : ` ${alts} alternative${alts === 1 ? " is" : "s are"} pending on this node.`;
  if (n.draft) {
    const denial = state === "ratified"
      ? "Denying leaves the answer as ratified."
      : state === "draft"
        ? "Denying leaves the earlier draft, which no one has confirmed either."
        : "Denying leaves the question open, with nothing behind it that holds.";
    return `Confirming ratifies the recommended text as the node. ${denial}${tail}`;
  }
  if (state === "ratified") return `Confirming keeps the answer as ratified.${tail}`;
  if (state === "draft") {
    return "Confirming ratifies the AI's draft as this node's answer. No one has confirmed it yet, "
      + `and the stamp it carries is not an answer.${tail}`;
  }
  return "No answer is drafted yet. The dialogue owes the next movement before there is anything "
    + `to confirm.${tail}`;
}

const WHOLE_RESPONSE_LBL = "Your ruling on the whole";
const EARLY_STAGES = new Set(["periagogic", "maieutic"]);
const LOCKED_NOTE = "Not open for a ruling yet: a confirmation recorded before the ruling stage is invalid, so everything below is shown and nothing below can be answered. The chip above opens the dialogue that moves this node on.";
const NO_WORDS_LINE = "No words of yours are recorded on this node yet. What the answer below says, the AI drafted.";

/* What confirming each choice of a reserved fact would mean, in the words the
 * `authority` node uses for them. Without these the most-repeated decision on
 * the page -- the authority class, on 41 nodes -- rendered as two bare
 * vocabulary words, breaking the same rule against showing a handle in place
 * of a sentence that the alternatives were fixed for. `persistence` is absent
 * because its choices are written per node and its `## Facts` prose already
 * explains them under the legend. */
const FACT_CHOICE_SAYS = {
  authority: {
    ratified: "You decided it, in this dialogue, and want to be asked before it changes.",
    delegated: "You hand this class of decision to the AI and do not want to be asked again.",
  },
  existence: {
    keep: "The question is its own question, and the node stays to answer it.",
    prune: "The question is another node's question asked twice: the node goes, and whatever it says that the other does not moves there.",
  },
};

// The question each reserved fact asks, in the words the author rules by. A
// decision labelled with a category says nothing about what is being asked,
// which is the second thing the author could not read on public/agency.
const FACT_QUESTIONS = {
  authority: "What class would a confirmation confer?",
  existence: "Is this node worth keeping at all?",
  persistence: "What would the ruling leave standing?",
};

function alignEsc(s) {
  return String(s == null ? "" : s).replace(/[&<>"]/g, (c) => (c === "&" ? "&amp;" : c === "<" ? "&lt;" : c === ">" ? "&gt;" : "&quot;"));
}

// Every markdown link renders as plain text: the alignment page is a flat,
// at-rest document with no per-node route to send a reader to, and almost
// every link this record writes is `[text](#some/node/id)` -- an address
// the browser resolves and this page cannot.
function alignMarks(t) {
  t = t.replace(/\[([^\]]+)\]\([^)\s]*\)/g, "$1");
  t = t.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
  t = t.replace(/(^|[\s(["])\*([^*\s][^*]*)\*/g, "$1<em>$2</em>");
  t = t.replace(/(^|[\s(["])_([^_\s][^_]*)_/g, "$1<em>$2</em>");
  return t;
}

function alignInline(s) {
  return String(s == null ? "" : s).split(/(`[^`]*`)/g).map((p) => {
    if (p.length > 1 && p.charAt(0) === "`" && p.charAt(p.length - 1) === "`") {
      return `<code>${alignEsc(p.slice(1, -1))}</code>`;
    }
    return alignMarks(alignEsc(p));
  }).join("");
}

const ALIGN_RE_BULLET = /^\s*([-*+])\s+(.*)$/;
const ALIGN_RE_ORDER = /^\s*(\d+)[.)]\s+(.*)$/;
const ALIGN_RE_BREAK = /^\s*(?:#{1,6}\s|```|>|[-*+]\s|\d+[.)]\s)/;
const ALIGN_RE_RULE = /^\s*(?:-{3,}|\*{3,}|_{3,})\s*$/;

/**
 * Port of the browser template's `mdBlocks`, adapted to keep a fenced
 * block's info string as `lang` so `renderProposal` can single out a
 * fenced ```markdown block -- a draft quoted into the account -- for its
 * own label; no other caller reads `lang`.
 *
 * @param {string} src
 * @returns {{type: string, lang?: string, html: string}[]}
 */
function alignBlocks(src) {
  const out = [];
  if (src == null || String(src).trim() === "") return out;
  const lines = String(src).replace(/\r\n?/g, "\n").split("\n");
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    if (!line.trim()) { i++; continue; }
    const fence = line.match(/^\s*```(\S*)\s*$/);
    if (fence) {
      const code = [];
      i++;
      while (i < lines.length && !/^\s*```\s*$/.test(lines[i])) { code.push(lines[i]); i++; }
      i++;
      out.push({ type: "code", lang: fence[1] || "", html: `<pre><code>${alignEsc(code.join("\n"))}</code></pre>` });
      continue;
    }
    if (ALIGN_RE_RULE.test(line)) { out.push({ type: "rule", html: "<hr>" }); i++; continue; }
    const head = line.match(/^\s*(#{1,6})\s+(.*)$/);
    if (head) {
      const lvl = Math.max(3, Math.min(6, head[1].length));
      const text = head[2].trim().replace(/\s+#+\s*$/, "");
      out.push({ type: "heading", html: `<h${lvl}>${alignInline(text)}</h${lvl}>` });
      i++;
      continue;
    }
    if (/^\s*>/.test(line)) {
      const quoted = [];
      while (i < lines.length && /^\s*>/.test(lines[i])) { quoted.push(lines[i].replace(/^\s*>\s?/, "")); i++; }
      out.push({ type: "quote", html: `<blockquote>${alignHtml(quoted.join("\n"))}</blockquote>` });
      continue;
    }
    if (ALIGN_RE_BULLET.test(line) || ALIGN_RE_ORDER.test(line)) {
      const ordered = !ALIGN_RE_BULLET.test(line);
      const re = ordered ? ALIGN_RE_ORDER : ALIGN_RE_BULLET;
      const items = [];
      while (i < lines.length) {
        const m = lines[i].match(re);
        if (m) { items.push(m[2]); i++; }
        else if (items.length && lines[i].trim() && /^\s{2,}\S/.test(lines[i])) { items[items.length - 1] += ` ${lines[i].trim()}`; i++; }
        else break;
      }
      const tag = ordered ? "ol" : "ul";
      out.push({ type: "list", html: `<${tag}>${items.map((t) => `<li>${alignInline(t)}</li>`).join("")}</${tag}>` });
      continue;
    }
    const para = [];
    while (i < lines.length && lines[i].trim() && !ALIGN_RE_BREAK.test(lines[i]) && !ALIGN_RE_RULE.test(lines[i])) {
      para.push(lines[i].trim());
      i++;
    }
    if (!para.length) { i++; continue; }
    out.push({ type: "para", html: `<p>${alignInline(para.join(" "))}</p>` });
  }
  return out;
}

function alignHtml(src) {
  return alignBlocks(src).map((b) => b.html).join("");
}

/**
 * `## Account`, with a fenced ```markdown block -- a recommended text
 * quoted into the account -- called out in its own labelled block so it is
 * never mistaken for "The node as it stands" or for the node's own
 * `## Recommendation`.
 *
 * @param {string} src
 * @returns {string}
 */
function renderAccount(src) {
  return alignBlocks(src).map((b) => {
    if (b.type === "code" && b.lang === "markdown") {
      return `<div class="quoted"><p class="blk-label">Quoted in the account; the sections above are the node</p>${b.html}</div>`;
    }
    return b.html;
  }).join("");
}

// Doc ids may not contain '/'; a node id always does.
function alignDocId(nodeId) {
  return String(nodeId).replace(/\//g, ":");
}

function alignSection(label, bodyHtml, cls) {
  return `<section${cls ? ` class="${cls}"` : ""}><p class="lbl">${alignEsc(label)}</p><div class="mdbody">${bodyHtml}</div></section>`;
}

/* ------------------------------- the edit: node against its draft ---- */

// Every frontmatter key the reader carries except `question` (the
// validator already holds the draft to the node's own question) and the
// dialogue-state keys -- `stage`, `alternatives`, `recommendation`,
// `review`, `depends` -- which are the dialogue's own state, removed at the
// recording, and never part of what the author rules on.
const EDIT_FM_KEYS = [
  "form", "authority", "under", "tier", "boost", "cites", "instrument",
  "after", "source", "relation", "defines", "shims", "order",
];

// Key-sorted JSON, for comparison only: two values are the same field
// value when their canonical forms match, whatever order YAML gave the
// keys. `authority` is compared as a whole, as one value, because that is
// what a stamp is.
function stableJson(v) {
  if (v === null || v === undefined) return "null";
  if (Array.isArray(v)) return `[${v.map(stableJson).join(",")}]`;
  if (typeof v === "object") {
    return `{${Object.keys(v).sort().map((k) => `${JSON.stringify(k)}:${stableJson(v[k])}`).join(",")}}`;
  }
  return JSON.stringify(v);
}

// YAML flow style, the compact one-line rendering of a frontmatter value:
// `rule`, `[a, b]`, `{class: ratified, by: claude, date: 2026-09-03}`, and
// `none` for an absent or empty one.
function flowYaml(v) {
  if (v === null || v === undefined) return "none";
  if (Array.isArray(v)) return v.length === 0 ? "none" : `[${v.map(flowYaml).join(", ")}]`;
  if (typeof v === "object") {
    const keys = Object.keys(v).filter((k) => v[k] !== null && v[k] !== undefined);
    if (keys.length === 0) return "none";
    return `{${keys.map((k) => `${k}: ${flowYaml(v[k])}`).join(", ")}}`;
  }
  return String(v);
}

/**
 * The frontmatter half of the edit: one entry per field whose value
 * differs between the node as it stands and its draft, in the reader's own
 * key order. The dialogue-state keys (see EDIT_FM_KEYS) are ignored.
 *
 * @param {object} node - a node as `read.mjs` returns it.
 * @param {{frontmatter: object}} draft - `node.draft`.
 * @returns {{field: string, before: string, after: string}[]}
 */
export function frontmatterEdits(node, draft) {
  const out = [];
  const fm = (draft && draft.frontmatter) || {};
  for (const key of EDIT_FM_KEYS) {
    const before = node[key] === undefined ? null : node[key];
    const after = fm[key] === undefined ? null : fm[key];
    if (stableJson(before) === stableJson(after)) continue;
    out.push({ field: key, before: flowYaml(before), after: flowYaml(after) });
  }
  return out;
}

const DIFF_TOKEN_CAP = 4000;

// A token is one run of non-whitespace plus the whitespace that followed
// it, normalized to a paragraph break or a single space, so the rendered
// diff keeps the text's paragraphs (the page sets `white-space: pre-wrap`
// on it) and reflows to the measure like every other body of prose on the
// page, whether or not the node's own file hard-wraps its lines. Only `t`
// is ever compared.
function diffTokens(text) {
  const out = [];
  const re = /(\S+)(\s*)/g;
  let m;
  const src = String(text == null ? "" : text);
  while ((m = re.exec(src)) !== null) {
    const ws = m[2] === "" ? "" : /\n[^\S\n]*\n/.test(m[2]) ? "\n\n" : " ";
    out.push({ t: m[1], ws });
  }
  return out;
}

// Longest common subsequence over two token lists, walked back into a flat
// op list. The table is filled from the end so the walk forward can be
// greedy, which keeps a run of insertions together rather than
// interleaving it with the deletions it replaces.
function lcsOps(a, b) {
  const n = a.length;
  const m = b.length;
  const w = m + 1;
  const dp = new Uint32Array((n + 1) * w);
  for (let i = n - 1; i >= 0; i -= 1) {
    for (let j = m - 1; j >= 0; j -= 1) {
      dp[i * w + j] = a[i].t === b[j].t
        ? dp[(i + 1) * w + (j + 1)] + 1
        : Math.max(dp[(i + 1) * w + j], dp[i * w + (j + 1)]);
    }
  }
  const ops = [];
  let i = 0;
  let j = 0;
  while (i < n && j < m) {
    if (a[i].t === b[j].t) { ops.push({ op: "same", tok: b[j] }); i += 1; j += 1; }
    else if (dp[(i + 1) * w + j] >= dp[i * w + (j + 1)]) { ops.push({ op: "del", tok: a[i] }); i += 1; }
    else { ops.push({ op: "ins", tok: b[j] }); j += 1; }
  }
  while (i < n) { ops.push({ op: "del", tok: a[i] }); i += 1; }
  while (j < m) { ops.push({ op: "ins", tok: b[j] }); j += 1; }
  return ops;
}

/**
 * A word-level diff of two section texts as a flat op list: `same` tokens
 * from the new text, `del` tokens from the old, `ins` tokens from the new.
 * The shared head and tail are matched off first, so the quadratic table
 * only ever covers what actually moved.
 *
 * Returns `null` -- the caller's cue to print the "too long to diff"
 * fallback -- when either side is longer than `cap` tokens, the one bound
 * on a table that is otherwise the product of the two lengths.
 *
 * @param {string|null} before
 * @param {string|null} after
 * @param {number} [cap]
 * @returns {{op: "same"|"del"|"ins", tok: {t: string, ws: string}}[]|null}
 */
export function wordDiff(before, after, cap = DIFF_TOKEN_CAP) {
  const a = diffTokens(before);
  const b = diffTokens(after);
  if (a.length > cap || b.length > cap) return null;
  let head = 0;
  while (head < a.length && head < b.length && a[head].t === b[head].t) head += 1;
  let tail = 0;
  while (
    tail < a.length - head
    && tail < b.length - head
    && a[a.length - 1 - tail].t === b[b.length - 1 - tail].t
  ) tail += 1;
  const ops = b.slice(0, head).map((tok) => ({ op: "same", tok }));
  ops.push(...lcsOps(a.slice(head, a.length - tail), b.slice(head, b.length - tail)));
  ops.push(...b.slice(b.length - tail).map((tok) => ({ op: "same", tok })));
  return ops;
}

// Consecutive ops of one kind become one <ins>/<del>; the run's own
// trailing whitespace is emitted outside the tag, so a struck-through or
// underlined run never swallows the space or newline after it.
function diffHtml(ops) {
  let html = "";
  let i = 0;
  while (i < ops.length) {
    const kind = ops[i].op;
    const run = [];
    while (i < ops.length && ops[i].op === kind) { run.push(ops[i].tok); i += 1; }
    const inner = run.map((tok, k) => alignEsc(tok.t) + (k < run.length - 1 ? tok.ws : "")).join("");
    const trailing = run[run.length - 1].ws;
    if (kind === "same") html += inner + trailing;
    else if (kind === "ins") html += `<ins>${inner}</ins>${trailing}`;
    else html += `<del>${inner}</del>${trailing}`;
  }
  return html;
}

function renderSectionDiff(label, before, after) {
  if (!(before || "").trim() && !(after || "").trim()) return "";
  const ops = wordDiff(before, after);
  const body = ops === null
    ? '<p class="none">Too long to diff: read the draft above against the node as it stands.</p>'
    : `<div class="diff">${diffHtml(ops)}</div>`;
  return `<p class="difflbl">${alignEsc(label)}</p>${body}`;
}

/* --------------------------------------------- the alternatives ----- */

/**
 * The divergence inversion for one alternative `alternativeName` of node
 * `n`: every other node's `depends` entry that names `n` is, on the leaf,
 * a decision the leaf stands under; here, on the ancestor, it is inverted
 * into what a ruling for this alternative would do. `keeps` is every node
 * whose `depends` entry names `n` under exactly this alternative -- a
 * ruling for it leaves that leaf's ground as recorded; `discards` is every
 * node whose `depends` entry names `n` under some other named alternative
 * -- a ruling for this one contradicts what that leaf stood under. Neither
 * list ever includes a plain, unqualified `depends` entry (an open
 * question waiting on `n`'s ruling generally, not a stand taken under one
 * particular alternative). Both sorted ascending; this is derived fresh
 * from the graph each time, never stored on the record.
 *
 * @param {{id: string}} n
 * @param {string} alternativeName
 * @param {object[]} allNodes - the full node list, `graph.nodes`.
 * @returns {{keeps: string[], discards: string[]}}
 */
function divergenceFor(n, alternativeName, allNodes) {
  const keeps = [];
  const discards = [];
  for (const other of allNodes) {
    for (const d of other.depends || []) {
      if (d.id !== n.id || d.alternative == null) continue;
      if (d.alternative === alternativeName) keeps.push(other.id);
      else discards.push(other.id);
    }
  }
  return { keeps: keeps.sort(), discards: discards.sort() };
}

// The one extra paragraph a divergence adds to an alternative's block (see
// renderDecision): what a ruling for this alternative keeps of the
// leaves standing under it, and, unless there are none, what it discards
// of the leaves standing under a different alternative of the same node.
function renderDivergenceParagraph(keeps, discards) {
  if (keeps.length === 0) {
    return `<p class="divergence">${alignEsc("A ruling for this keeps nothing recorded.")}</p>`;
  }
  let html = `<p class="divergence">A ruling for this keeps: <em>${keeps.map(alignEsc).join(", ")}</em>.`;
  if (discards.length > 0) {
    html += ` It discards: <em>${discards.map(alignEsc).join(", ")}</em>.`;
  }
  return `${html}</p>`;
}

// What the recommendation itself carries, beneath the node it proposes: the
// alternative it adopts, its boldness, whether its pin has gone stale under
// it, and the persistence a confirmation would leave. It carries no class:
// the class a confirmation confers is the `authority` fact
// (commons.systems/disposition-graph/dialogue).
function renderRecommendation(n) {
  if (!n.recommendation) {
    return '<p class="recline none">No recommendation yet.</p>';
  }
  const rec = n.recommendation;
  let pills = `<span class="pill rec-adopts">adopts: ${alignEsc(rec.adopts)}</span>`
    + `<span class="pill rec-bold-${alignEsc(rec.boldness)}">boldness: ${alignEsc(rec.boldness)}</span>`;
  if (n.recommendationStale) {
    pills += '<span class="pill rec-stale">standing text changed since the recommendation</span>';
  }
  const shims = persistenceShims(n);
  const persistence = shims.length === 0
    ? '<p class="persist">Persistence: standing.</p>'
    : `<p class="persist">Persistence: standing, with ${shims.length} shim${shims.length === 1 ? "" : "s"}:</p>`
      + `<ul class="shims">${shims.map((s) => `<li>${alignInline(s.artifact)}</li>`).join("")}</ul>`;
  return `<p class="pills recline">${pills}</p>${persistence}`;
}

/* ------------------------- the recommendation and the review --------- */

// The shims a confirmation would leave standing: the draft's when the node
// has one that declares any, the node's own otherwise.
function persistenceShims(n) {
  const draftShims = n.draft && n.draft.frontmatter ? n.draft.frontmatter.shims : null;
  if (Array.isArray(draftShims) && draftShims.length > 0) return draftShims;
  return Array.isArray(n.shims) ? n.shims : [];
}

function renderReview(n) {
  if (!n.review) {
    return '<section class="rev"><p class="lbl">The review</p><p class="none">Not yet reviewed.</p></section>';
  }
  const verdict = n.review.verdict === "forward" ? "forwarded" : "kicked back";
  let pills = `<span class="pill rev-${alignEsc(n.review.verdict)}">${alignEsc(verdict)}</span>`
    + `<span class="pill rev-strength">counter-argument: ${alignEsc(n.review.strength)}</span>`
    + `<span class="pill rev-date">${alignEsc(n.review.date)}</span>`;
  if (n.reviewStale) pills += '<span class="pill rev-stale">draft changed since the review</span>';
  return `<section class="rev"><p class="lbl">The review</p><p class="pills">${pills}</p></section>`;
}

/* --------------------------- the ruling screen ------------------------
 *
 * commons.systems/disposition-graph/alignment-page: one node at a time, on
 * a three-column screen, in the ruling order. The rail carries the metrics
 * and every unanswered node. The middle column carries everything the
 * ruling asks: the stage's own ask, the decisions, the ruling on the whole,
 * what a ruling here makes decidable, then the review, the author's words
 * and the account. The right-hand column carries the rendered disposition
 * and nothing else (the author's refinement of 2026-09-04).
 */

// The browser's published address, read out of the record rather than
// written here: the shim that names it is declared on
// commons.systems/disposition-graph/projection. A metric links to the
// disposition it instruments at that address, since this page addresses no
// node of its own. Null when no shim names it, and then a metric renders
// unlinked rather than pointing nowhere.
function browserAddress(graph) {
  for (const n of graph.nodes || []) {
    for (const s of n.shims || []) {
      const text = String(s.artifact || "");
      if (!/browser/i.test(text)) continue;
      const m = text.match(/https:\/\/\S*?artifact\/[0-9a-f-]+/i);
      if (m) return m[0];
    }
  }
  return null;
}

// The four metrics, each a signal of a recorded disposition and never a
// count for its own sake, as this page's answer requires. `of` names the
// node the metric instruments; the rail links to it.
/* ------------------------- the session, launched or copied ------------- */

/* The instruction that opens the dialogue on one node. One function, because
 * the launch link and the copy control must carry the same text: two controls
 * that claim to do the same thing and emit different text is the defect this
 * exists to prevent (commons.systems/disposition-graph/ruling-transport). */
function alignInstruction(nodeId) {
  return `/align ${nodeId}`;
}

const SESSION_BASE = "https://claude.ai/code";

/* The repository a launched session opens against, read out of the shim that
 * declares the launch control rather than written here -- the same way the
 * browser's address is read from its own shim. `/align` is a project skill
 * the harness finds only in this checkout, so a link that pre-fills the
 * prompt and selects no repository opens a session without the skill.
 * Null when no shim names one, and then the link carries the prompt alone. */
function sessionRepo(graph) {
  for (const n of graph.nodes || []) {
    for (const s of n.shims || []) {
      const m = String(s.artifact || "").match(/repositories=([A-Za-z0-9._-]+\/[A-Za-z0-9._-]+)/);
      if (m) return m[1];
    }
  }
  return null;
}

/* `prompt` and `repositories` are supported query parameters of
 * https://claude.ai/code (code.claude.com/docs/en/web-quickstart). The link
 * pre-fills the form and does not submit it, and the page says so rather
 * than implying a click is the whole action. */
function sessionSeed(instruction, repo) {
  const q = `prompt=${encodeURIComponent(instruction)}`;
  return repo === null || repo === undefined
    ? `${SESSION_BASE}?${q}`
    : `${SESSION_BASE}?${q}&repositories=${encodeURIComponent(repo)}`;
}

const SITTING_COPY_TITLE = "Copy the instruction that carries every response into a session by hand. This is the route the author uses.";
const SITTING_RECORD_TITLE = "Write every staged response into this artifact's own record, where a session reads them back without a paste. A buffer and never the record: nothing ruled here exists only there.";
const LAUNCH_TITLE = "Open an alignment session on this node. A stub: the link pre-fills the form and does not submit it, and Claude Code on the web is a research preview that needs a signed-in account.";
const COPY_TITLE = "Copy the instruction that opens the dialogue on this node.";
const LAUNCH_GLYPH = "\u2197";
const COPY_GLYPH = "\u29C9";

/* The stage as a chip carrying the two routes into the dialogue: a link that
 * opens a session on this node, and a copy of the instruction that starts
 * one. At every stage but `ruling` these are what the page offers instead of
 * a control, since a confirmation recorded before the ruling stage is invalid
 * (the author's ruling of 2026-09-04). */
function renderStageChip(n, repo) {
  const instruction = alignInstruction(n.id);
  const href = sessionSeed(instruction, repo);
  return `<span class="chip stage-${alignEsc(n.stage)}">`
    + `<span class="chipname">${alignEsc(n.stage)}</span>`
    + `<a class="chipbtn stub" href="${alignEsc(href)}" target="_blank" rel="noopener"`
    + ` title="${alignEsc(LAUNCH_TITLE)}" aria-label="Open an alignment session on this node (a stub)">${LAUNCH_GLYPH}</a>`
    + `<button type="button" class="chipbtn" data-copy="${alignEsc(instruction)}"`
    + ` title="${alignEsc(COPY_TITLE)}" aria-label="Copy the instruction for this node">${COPY_GLYPH}</button>`
    + "</span>";
}

function alignmentMetrics(items) {
  const first = items[0] || null;
  return [
    {
      key: "open",
      value: items.length,
      of: "commons.systems/disposition-graph/unanswered",
      why: "Nodes the author has not confirmed. Every node is unanswered until they do, so this is the outstanding authority.",
    },
    {
      key: "ruleable",
      value: items.filter((n) => n.stage === "ruling").length,
      of: "commons.systems/disposition-graph/clean-context-review",
      why: "Nodes whose clean-context review is behind them. The review is what stands between a draft and the author, so this is what can be ruled now.",
    },
    {
      key: "next settles",
      value: first && typeof first.settles === "number" ? first.settles : 0,
      of: "commons.systems/disposition-graph/alignment-order",
      why: "What a ruling on the first node in the order would make decidable. The order puts the ruling that settles the most first, so this is what one ruling buys.",
    },
    {
      key: "stale",
      value: items.filter((n) => n.recommendationStale || n.reviewStale).length,
      of: "commons.systems/disposition-graph/frontier-consistency",
      why: "Nodes whose recommendation or review pin no longer matches the text it read. This is how much of what looks ruleable rests on a reading of text that has moved.",
    },
  ];
}

function renderMetrics(items, browser) {
  const cells = alignmentMetrics(items).map((m) => {
    const inner = `<dt>${alignEsc(m.key)}</dt><dd class="num">${alignEsc(m.value)}</dd>`;
    const title = `${m.why} Instruments ${m.of}.`;
    return browser === null
      ? `<div class="metric" title="${alignEsc(title)}">${inner}</div>`
      : `<a class="metric" href="${alignEsc(browser)}#${alignEsc(m.of)}" target="_blank" rel="noopener" title="${alignEsc(title)}">${inner}</a>`;
  }).join("");
  return `<dl class="metrics">${cells}</dl>`;
}

/* ------------------------- the decisions this ruling asks ------------- */

// The decisions a ruling on this node asks: its own answer, where
// alternatives are pending on it, and its asking facts. A decision is asked
// whenever its boldness is anything but low and folds unasked into the
// right-hand column when its boldness is low -- and because boldness runs
// from the AI's own knowledge against the record, high boldness is low
// confidence, so the fold is on `low` and never on `high`.
function decisionsFor(n, allNodes) {
  const out = [];
  const alts = Array.isArray(n.alternatives) ? n.alternatives : [];
  const rec = n.recommendation || null;
  if (alts.length > 0) {
    const text = n.alternativesText || {};
    const divergences = alts.map((a) => divergenceFor(n, a.name, allNodes));
    const showDivergence = divergences.some((d) => d.keeps.length > 0);
    const state = standingState(n);
    // Nothing stands here to keep, so the choice is not offered -- unless a
    // recommendation adopts it anyway, and then it is shown for what it is
    // rather than dropped, leaving the recommendation's mark without a row.
    const keep = state !== "none" || (rec && rec.adopts === STANDING_CHOICE)
      ? [{
        value: STANDING_CHOICE,
        label: KEEP_LABELS[state],
        pills: [{ cls: "alt-src", text: KEEP_PILLS[state] }],
        prose: "",
        divergence: "",
      }]
      : [];
    const choices = [
      ...keep,
      ...alts.map((a, i) => ({
        value: a.name,
        label: a.name,
        pills: [
          { cls: "alt-src", text: a.source },
          ...(a.ref ? [{ cls: "alt-ref mono", text: a.ref }] : []),
        ],
        prose: text[a.name] || "",
        divergence: showDivergence
          ? renderDivergenceParagraph(divergences[i].keeps, divergences[i].discards)
          : "",
      })),
    ];
    out.push({
      name: "answer",
      // The decision is labelled with the question it asks, which for the
      // node's own answer is the node's own question.
      label: n.question || "The answer",
      // With no recommendation yet there is no boldness to fold on, and a
      // decision nobody has recommended is asked, never folded away.
      boldness: rec ? rec.boldness : null,
      adopts: rec ? rec.adopts : null,
      choices,
    });
  }
  const factText = n.factsText || {};
  for (const f of n.facts || []) {
    out.push({
      name: f.name,
      label: FACT_QUESTIONS[f.name] || f.name,
      boldness: f.boldness,
      adopts: f.adopts,
      ruling: f.ruling || null,
      // The '## Facts' subsection explains the fact's choices as a set, so
      // it sits under the legend and not on any one row.
      prose: factText[f.name] || "",
      choices: f.choices.map((c) => ({
        value: c,
        label: c,
        pills: [],
        prose: (FACT_CHOICE_SAYS[f.name] || {})[c] || "",
        divergence: "",
      })),
    });
  }
  return out;
}

/* One choice, leading with what it would answer. The alternative's name is
 * how a ruling is filed in the record; the sentence beneath it in
 * `## Alternatives` is the decision. Rendering the name and folding the
 * sentence into the drill-down left the author a list of identifiers, which
 * is what they reported reading on public/agency; it is progressive
 * disclosure on the wrong axis. A fact's choices carry no such sentence --
 * `keep` and `prune` are their own -- so those rows lead with the value. */
function renderChoice(doc, d, c, locked) {
  const adopted = c.value === d.adopts;
  const pills = c.pills.map((p) => `<span class="pill ${p.cls}">${alignEsc(p.text)}</span>`).join("")
    + (adopted ? `<span class="pill alt-adopted">${alignEsc(ADOPTED_MARK)}</span>` : "");
  const lead = c.prose
    ? `<span class="choicesays">${alignInline(firstSentences(c.prose))}</span>`
      + `<span class="choicename mono handle">${alignEsc(c.label)}</span>`
    : `<span class="choicename">${alignEsc(c.label)}</span>`;
  const rest = c.prose ? restOf(c.prose) : "";
  const drill = rest || c.divergence
    ? '<details class="drill"><summary>The rest of what it says</summary>'
      + (rest ? `<div class="mdbody">${alignHtml(rest)}</div>` : "")
      + c.divergence
      + "</details>"
    : "";
  return `<li class="choice${adopted ? " adopted" : ""}">`
    + `<label class="choicelbl"><input type="radio" name="dec:${alignEsc(doc)}:${alignEsc(d.name)}" value="${alignEsc(c.value)}" data-choice${locked ? " disabled" : ""}>`
    + `${lead}</label>${pills}${drill}</li>`;
}

/* The lead of a choice's prose: enough to decide by, with the remainder
 * behind the drill-down. One paragraph, or as many whole sentences of it as
 * the cap allows, so that a row stays a row.
 *
 * The cap is set by measurement over the 212 alternative prose blocks in the
 * graph on 2026-09-04, counting how many leads it forces to break inside a
 * sentence rather than at the end of one: 200 breaks 59%, 260 breaks 32%,
 * 320 breaks 16%, 400 breaks 3%, 480 breaks 1%. 400 is the knee -- it ends
 * all but seven leads on a full stop, at a median lead of 320 characters,
 * about four lines of the middle column -- and past it the median grows
 * without buying much. A row that breaks mid-sentence makes the author open
 * the drill-down to finish the thought, which is the fold this answer
 * exists to undo. */
const CHOICE_LEAD_CHARS = 400;
function firstSentences(prose) {
  const para = prose.trim().split(/\n\s*\n/)[0].replace(/\s+/g, " ").trim();
  if (para.length <= CHOICE_LEAD_CHARS) return para;
  const cut = para.slice(0, CHOICE_LEAD_CHARS);
  const at = Math.max(cut.lastIndexOf(". "), cut.lastIndexOf("; "));
  return at > 80 ? para.slice(0, at + 1) : `${cut.replace(/\s+\S*$/, "")}\u2026`;
}
// What the drill-down holds: the paragraphs the lead did not take. Where the
// lead is the whole first paragraph that is every paragraph after it; where
// the lead was cut short of it, the drill repeats from the start, so that
// nothing the record says about a choice is only ever shown truncated.
function restOf(prose) {
  const trimmed = prose.trim();
  const paras = trimmed.split(/\n\s*\n/);
  const firstWhole = paras[0].replace(/\s+/g, " ").trim();
  if (firstSentences(trimmed) !== firstWhole) return trimmed;
  return paras.slice(1).join("\n\n");
}

function renderDecision(doc, d, locked) {
  const rows = d.choices.map((c) => renderChoice(doc, d, c, locked)).join("");
  const reject = `<li class="choice reject">`
    + `<label class="choicelbl"><input type="radio" name="dec:${alignEsc(doc)}:${alignEsc(d.name)}" value="${alignEsc(REJECT_CHOICE)}" data-choice${locked ? " disabled" : ""}>`
    + `<span class="choicename">${alignEsc(REJECT_LABEL)}</span></label></li>`;
  const ruled = d.ruling
    ? `<p class="ruled">Ruled ${alignEsc(d.ruling.response)} on <span class="mono">${alignEsc(d.ruling.choice)}</span>, ${alignEsc(d.ruling.date)}.</p>`
    : "";
  const why = d.prose ? `<div class="mdbody decwhy">${alignHtml(d.prose)}</div>` : "";
  const bold = d.boldness
    ? `<span class="pill rec-bold-${alignEsc(d.boldness)}">boldness: ${alignEsc(d.boldness)}</span>`
    : '<span class="pill rec-bold-none">no recommendation yet</span>';
  return `<fieldset class="decision" data-decision="${alignEsc(d.name)}">`
    + `<legend class="declbl">${alignEsc(d.label)}${bold}</legend>`
    + ruled
    + why
    + `<ul class="choices">${rows}${reject}</ul>`
    + `<textarea class="note dec-note" data-decision-text rows="2" placeholder="${alignEsc(DECISION_NOTE_PLACEHOLDER)}"${locked ? " disabled" : ""} hidden></textarea>`
    + "</fieldset>";
}

function renderDecisions(n, allNodes, locked) {
  const doc = alignDocId(n.id);
  const decisions = decisionsFor(n, allNodes);
  const asked = decisions.filter((d) => d.boldness !== "low");
  const folded = decisions.filter((d) => d.boldness === "low");
  const body = asked.length === 0
    ? `<p class="none">${alignEsc(NOTHING_ASKED)}</p>`
    : asked.map((d) => renderDecision(doc, d, locked)).join("");
  const foldline = folded.length === 0
    ? ""
    : `<p class="folded">${alignEsc(FOLDED_LEAD)} `
      + folded.map((d) => `<span class="mono">${alignEsc(d.label)}: ${alignEsc(d.adopts)}</span>`).join(", ")
      + ".</p>";
  return `<section class="decisions"><p class="lbl">${alignEsc(DECISIONS_LBL)}</p>${body}${foldline}</section>`;
}

/* ------------------------- the asking column --------------------------- */

// The unanswered children of this node, and the open questions that name it
// in `depends`: indications of what a ruling here makes decidable, shown in
// the asking column and never as rows to rule from, since every node is
// ruled from the rail in its own turn in the one order.
function askIndications(n, allNodes) {
  const children = allNodes
    .filter((o) => o.stage && (o.under || []).includes(n.id))
    .map((o) => ({ id: o.id, question: o.question, how: "under it" }));
  const waiting = allNodes
    .filter((o) => o.stage && (o.depends || []).some((d) => d.id === n.id))
    .map((o) => ({
      id: o.id,
      question: o.question,
      how: (o.depends.find((d) => d.id === n.id).alternative
        ? `waits on ${o.depends.find((d) => d.id === n.id).alternative}`
        : "waits on this ruling"),
    }));
  const seen = new Set();
  const all = [...children, ...waiting].filter((x) => (seen.has(x.id) ? false : seen.add(x.id)));
  if (all.length === 0) return "";
  const items = all.map((x) => (
    `<li><span class="indq">${alignEsc(x.question || x.id)}</span>`
    + `<span class="meta mono">${alignEsc(x.how)}</span>`
    + `<span class="indid mono">${alignEsc(x.id)}</span></li>`
  )).join("");
  return `<section class="indications"><p class="lbl">${alignEsc(INDICATIONS_LBL)} (${all.length})</p>`
    + `<p class="hint">${alignEsc(INDICATIONS_HINT)}</p><ul class="indlist">${items}</ul></section>`;
}

/* Everything the ruling asks, in the order the column is read
 * (commons.systems/disposition-graph/alignment-page, the author's refinement
 * of 2026-09-04): the stage's own ask, then the decisions, then the ruling on
 * the whole, then what a ruling here makes decidable, then the review, the
 * author's words and the AI's account as drill-downs. The right-hand column
 * holds the disposition and nothing else.
 *
 * At the periagogic and maieutic stages what the node owes is the author's
 * words, so the whole-node control leads the column under the stage's own
 * legend and the decisions follow it, marked as running ahead of the
 * dialogue. At review and ruling the decisions lead and the control follows.
 * The control is the same one either way: one textarea bound to one field.
 */
function renderAsk(n, allNodes, doc, repo) {
  // Only the ruling stage takes a response. A confirmation recorded on a node
  // that has not reached it is invalid, so everywhere else the decisions, the
  // choices and the recommendation are all rendered and every input among
  // them is disabled: the author sees exactly what will be asked and cannot
  // yet answer it (the author's ruling of 2026-09-04).
  const locked = n.stage !== "ruling";
  const hint = STAGE_HINT[n.stage];
  const lead = `<p class="stagelead">${renderStageChip(n, repo)}`
    + (hint ? `<span class="stagehint">${alignEsc(hint)}</span>` : "")
    + "</p>";
  const gate = locked
    ? `<p class="locked">${alignEsc(LOCKED_NOTE)}</p>`
    : "";
  const decisions = renderDecisions(n, allNodes, locked);
  const whole = renderWholeResponse(n, doc, locked);
  const words = n.disposition
    ? `<details class="drill words"${EARLY_STAGES.has(n.stage) ? " open" : ""}><summary>The author's words</summary><div class="mdbody">${alignHtml(n.disposition)}</div></details>`
    : (EARLY_STAGES.has(n.stage) ? `<p class="nowords">${alignEsc(NO_WORDS_LINE)}</p>` : "");
  const account = n.account
    ? `<details class="drill"><summary>The AI's account</summary><div class="mdbody">${renderAccount(n.account)}</div></details>`
    : "";
  // With the inputs locked there is no control to lead with and no reason to
  // reorder: the column reads decisions, the ruling on the whole, what a
  // ruling here makes decidable, the review, the author's words, the account.
  return lead + gate + decisions + whole
    + askIndications(n, allNodes)
    + renderReview(n)
    + words
    + account;
}

/* ------------------------- the node as it would stand ----------------- */

/* The disposition and nothing else. No control, no caption, no indication
 * and no drill-down shares this column: its one job is to show the author
 * the thing they are ruling on, and every sentence of apparatus in it is a
 * sentence to read past to reach that
 * (commons.systems/disposition-graph/alignment-page).
 *
 * Where an answer stands the column leads with the edit this ruling would
 * make and then the node it would leave; where none does it shows the whole.
 * "Stands" is measured by the stamp's class and never by its presence: a
 * deferred stamp is not an answer, so a deferred node with a fence is a
 * draft amending a draft and the diff is still what the author needs to see.
 */
function renderPane(n) {
  const hasAnswer = typeof n.answer === "string" && n.answer.length > 0;
  let body;
  if (n.draft) {
    const d = n.draft;
    const whole = `<div class="mdbody">${alignHtml(d.sections.Answer)}${alignHtml(d.sections.Rationale)}</div>`;
    if (hasAnswer) {
      const fm = frontmatterEdits(n, d);
      const fmHtml = fm.length === 0
        ? '<p class="none">No frontmatter field changes.</p>'
        : `<ul class="fmdiff">${fm.map((e) => `<li><code>${alignEsc(e.field)}</code>: <span class="was">${alignEsc(e.before)}</span> <span class="arrow">&rarr;</span> <span class="now">${alignEsc(e.after)}</span></li>`).join("")}</ul>`;
      const diffs = renderSectionDiff("Answer", n.answer, d.sections.Answer)
        + renderSectionDiff("Rationale", n.rationale, d.sections.Rationale);
      // What the diff is against, said on the diff. The author's finding of
      // 2026-09-03 was that a node "still indicates that it is an edit to a
      // confirmed disposition (there appears to be a ground version that is
      // being diffed) even though no node is yet confirmed" -- raised on
      // commons.systems/disposition-graph/purpose, which has an answer, a
      // fence and no stamp at all. The diff itself is what the author needs
      // to see and stays; what was wrong was letting it imply its base had
      // standing.
      const base = standingState(n) === "ratified"
        ? "The edit, against the ratified answer"
        : "The edit, against a draft no one has confirmed";
      body = `<p class="lbl edit-lbl">${alignEsc(base)}</p><div class="edit">${fmHtml}${diffs}</div>`
        + `<p class="lbl edit-lbl">The node it would leave</p>${whole}`;
    } else {
      body = whole;
    }
  } else if (hasAnswer) {
    body = `<div class="mdbody">${alignHtml(n.answer)}${n.rationale ? alignHtml(n.rationale) : ""}</div>`;
  } else {
    body = `<p class="none">${alignEsc(NO_ANSWER_LINE)}</p>`;
  }
  return '<aside class="col-pane">'
    + `<section class="stands"><p class="lbl">${alignEsc(PANE_LBL)}</p>${body}</section>`
    + "</aside>";
}

/* The whole-node response: the three responses the unanswered node opens and
 * this page adds none, the recommendation's own pills, and the caption saying
 * what a confirmation would do -- on the control that would do it, so that it
 * cannot contradict the decisions from the far side of the screen. */
function renderWholeResponse(n, doc, locked) {
  const opts = RESPONSE_CHOICES.map((c) => (
    `<label class="segopt"><input type="radio" name="opt:${alignEsc(doc)}" value="${alignEsc(c.value)}" data-option data-note-label="${alignEsc(c.note)}"${locked ? " disabled" : ""}><span>${alignEsc(c.label)}</span></label>`
  )).join("");
  return '<div class="response">'
    + '<fieldset class="controls" data-controls>'
    + `<legend class="lbl">${alignEsc(WHOLE_RESPONSE_LBL)}</legend>`
    + renderRecommendation(n)
    + `<p class="caption">${alignEsc(wholeCaption(n))}</p>`
    + `<div class="seg">${opts}</div>`
    + `<label class="note-lbl" data-note-lbl for="note-${alignEsc(doc)}">A note, edits, or feedback</label>`
    + `<textarea class="note" id="note-${alignEsc(doc)}" data-field="text" rows="3"${locked ? " disabled" : ""}></textarea>`
    + "</fieldset>"
    + '<p class="state" data-state hidden></p>'
    + "</div>";
}

function renderAlignmentItem(n, allNodes, repo) {
  const under = n.under || [];
  const doc = alignDocId(n.id);
  const stamp = n.authority
    ? `${n.authority.class} · ${n.authority.by} · ${n.authority.date}`
    : "no stamp";
  const rank = typeof n.rank === "number" ? n.rank.toFixed(4) : "—";

  // With no answer and no fence there is no disposition to render, so the
  // right-hand column is one line and reserving half the screen for it leaves
  // the viewport half empty for the whole of the item. Fifteen nodes.
  const bare = !(typeof n.answer === "string" && n.answer.length > 0) && !n.draft;
  let html = `<article class="item${bare ? " nostand" : ""}" id="item-${alignEsc(doc)}" data-item data-id="${alignEsc(n.id)}" data-doc="${alignEsc(doc)}" data-stage="${alignEsc(n.stage)}" hidden>`;
  html += '<div class="col-ask">';
  html += `<h2 class="iq">${alignEsc(n.question || n.id)}</h2>`;
  html += `<p class="idv mono">${alignEsc(n.id)}</p>`;
  html += '<p class="eyebrow">'
    + `<span class="meta mono">${alignEsc(n.graph)}</span>`
    + (typeof n.settles === "number" ? `<span class="meta mono num">settles ${alignEsc(n.settles)}</span>` : "")
    // The alternatives pending on a node are shown beside its settling
    // count: they are what tells the author what a sitting will cost, and
    // they order nothing (commons.systems/disposition-graph/alignment-order).
    + (n.alternatives && n.alternatives.length > 0
      ? `<span class="meta mono num">${alignEsc(n.alternatives.length)} alternative${n.alternatives.length === 1 ? "" : "s"}</span>`
      : "")
    + `<span class="meta mono num">rank ${alignEsc(rank)}</span>`
    + `<span class="meta mono">${alignEsc(stamp)}</span>`
    + `<span class="meta mono parents">${under.length ? `under ${alignEsc(under.join(", "))}` : "a root"}</span>`
    + "</p>";
  html += renderAsk(n, allNodes, doc, repo);
  html += "</div>";
  html += renderPane(n);
  html += "</article>";
  return html;
}

/**
 * Every node carrying a `stage`, in one flat ruling order across every
 * graph the manifest names: `settles` descending, then `rank` descending,
 * then id. The alignment frontier's dependencies cross graphs --
 * `commons.systems/public/agency` is the sole root and every
 * `disposition-graph` node hangs under it -- so a graph is a label on a
 * node here, never a precedence; ordering graph by graph would put a
 * descendant's ruling ahead of its own ancestor's, exactly what the ruling
 * order exists to prevent.
 *
 * `graphs` lists every declared graph in the manifest's own order, its
 * `about` text, and how many of `items` belong to it, with a graph a node
 * names but the manifest does not declare appended after the declared ones
 * rather than dropped, so no open dialogue's graph can go missing. The page
 * renders only the label, on each rail row: the pagehead that carried the
 * `about` lines and the per-stage counts liquidated without a disposition,
 * on the author's ruling of 2026-09-03
 * (commons.systems/disposition-graph/alignment-page).
 *
 * @param {{graphs?: object, nodes?: object[]}} graph
 * @returns {{items: object[], graphs: {graph: string, label: string, about: string|null, count: number}[]}}
 */
export function orderAlignmentItems(graph) {
  const items = (graph.nodes || []).filter((n) => n.stage).sort((a, b) => {
    const bs = b.settles ?? 0;
    const as = a.settles ?? 0;
    if (bs !== as) return bs - as;
    return b.rank !== a.rank ? b.rank - a.rank : (a.id < b.id ? -1 : a.id > b.id ? 1 : 0);
  });

  const declared = graph.graphs && typeof graph.graphs === "object" ? Object.keys(graph.graphs) : [];
  const names = [...declared];
  for (const n of items) if (!names.includes(n.graph)) names.push(n.graph);

  const graphs = names.map((name) => {
    const entry = (graph.graphs && graph.graphs[name]) || {};
    return {
      graph: name,
      label: name,
      about: typeof entry.about === "string" ? entry.about : null,
      count: items.filter((n) => n.graph === name).length,
    };
  });

  return { items, graphs };
}

function alignmentPageHtml(graph, items, graphs) {
  const total = items.length;
  const browser = browserAddress(graph);
  const repo = sessionRepo(graph);
  const graphOf = new Map(graphs.map((g) => [g.graph, g.label]));

  // The rail is the only view of the whole frontier once one node is shown
  // at a time, which is why the metrics sit at its top and why it lists
  // every node, filtering and paging nothing.
  const railHtml = `<ol class="tree">${items.map((n, i) => {
    const doc = alignDocId(n.id);
    const settles = typeof n.settles === "number" ? n.settles : 0;
    return `<li><a href="#item-${alignEsc(doc)}" data-rail data-doc="${alignEsc(doc)}" aria-current="false">`
      + `<span class="dot stage-${alignEsc(n.stage)}" aria-hidden="true"></span>`
      + `<span class="rq">${alignEsc(n.question || n.id)}</span>`
      + `<span class="rmeta mono">${alignEsc(i + 1)} · settles ${alignEsc(settles)}`
      + ` · ${alignEsc(graphOf.get(n.graph) || n.graph)}</span>`
      + '<span class="mark" data-mark></span></a></li>';
  }).join("")}</ol>`;

  const itemsHtml = items.map((n) => renderAlignmentItem(n, graph.nodes, repo)).join("");

  const emptyHtml = total === 0
    ? '<p class="empty">Nothing is unanswered. Every disposition has been confirmed by the author.</p>'
    : "";
  const refline = alignEsc([graph.module, graph.ref].filter(Boolean).join(" · "));

  return `<header class="mast">
  <div class="mast-in">
    <div class="brand">
      <span class="wordmark">Alignment</span>
      <span class="refline">${refline}</span>
      <span id="module-name" hidden>${alignEsc(graph.module || "")}</span>
    </div>
    <nav class="tools" aria-label="Actions">
      <button type="button" class="tbtn" id="btn-wide" aria-pressed="false">Widen the node</button>
      <button type="button" class="tbtn" id="btn-theme">Theme: auto</button>
    </nav>
  </div>
</header>
<div class="shell">
  <nav class="nav" id="nav" aria-label="The unanswered frontier, in the ruling order">
    ${renderMetrics(items, browser)}
    <div id="tree">${railHtml}</div>
  </nav>
  <main id="main">
    <p class="notice" id="notice" hidden></p>
    ${itemsHtml}
    ${emptyHtml}
  </main>
</div>
<footer class="foot" id="foot">
  <div class="foot-in">
    <span class="foot-count" id="staged-count">0 responses staged</span>
    <span class="foot-note" id="foot-note"></span>
    <span class="foot-acts">
      <a class="sbtn stub" id="btn-launch" href="${alignEsc(sessionSeed("/align", repo))}" target="_blank" rel="noopener" title="${alignEsc(LAUNCH_TITLE)}">${LAUNCH_GLYPH} Open a session</a>
      <button type="button" class="sbtn" id="btn-copy" title="${alignEsc(SITTING_COPY_TITLE)}">Copy the instruction</button>
      <button type="button" class="sbtn" id="btn-submit" disabled title="${alignEsc(SITTING_RECORD_TITLE)}">Record 0 for a session</button>
    </span>
  </div>
</footer>`;
}

/**
 * Render every node carrying a `stage` into
 * `packages/disposition/alignment-template.html`: the open dialogue the
 * author rules on, one flat page, in one ruling order across every graph
 * (see `orderAlignmentItems`). See the section comment above for why this
 * renders to HTML in Node rather than inlining JSON for a client-side
 * router, unlike `build()`.
 *
 * @param {string} template
 * @param {{module?: string, ref?: string|null, graphs?: object, nodes: object[]}} graph
 * @returns {string}
 */
export function buildAlignment(template, graph) {
  if (!template.includes(ALIGNMENT_MARKER)) throw new Error(`template has no ${ALIGNMENT_MARKER} marker`);
  const { items, graphs } = orderAlignmentItems(graph);
  const block = alignmentPageHtml(graph, items, graphs);
  return template.replace(ALIGNMENT_MARKER, () => block);
}

// Builds the browser page only when opts.out is given -- --rules and
// --ancestry are independent outputs that do not need it (see writeRules,
// writeAncestry), and check() only makes sense against the page's contract.
// check() runs against the full graph; excludeUnaligned() is applied only to
// what build() actually receives (see excludeUnaligned's own doc comment).
export async function project(opts) {
  const graph = await loadGraph(opts);
  if (!opts.out) return { out: null, html: null, graph, warnings: [] };
  const warnings = check(graph);
  const template = await readFile(resolve(HERE, "browser-template.html"), "utf8");
  const html = build(template, excludeUnaligned(graph));
  const out = resolve(opts.out);
  await mkdir(dirname(out), { recursive: true });
  await writeFile(out, html);
  return { out, html, graph, warnings };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  const opts = parseArgs(process.argv.slice(2));
  await runCli(opts);
}

// `readGraph` either returns a fully valid graph or throws with every
// problem it found and no partial data at all -- there is no "graph, plus
// a list of what's wrong with it" to render around. Rendering the frontier
// or the browser anyway on a graph that fails validation would need that
// contract to change everywhere `readGraph` is read from (validate.mjs,
// every output here, every test), which is a larger change than this
// unit's dialogue rules; the CLI's obligation ends at reporting that it
// cannot, cleanly, in the reader's own per-line message style, rather than
// an uncaught exception's raw stack trace.
async function runCli(opts) {
  let out, html, graph, warnings;
  try {
    ({ out, html, graph, warnings } = await project(opts));
  } catch (err) {
    process.stderr.write(`${err.message}\n`);
    process.exitCode = 1;
    return;
  }

  if (opts.rules) {
    const result = await writeRules(graph, opts.rules);
    for (const f of result.written) process.stdout.write(`wrote ${f}\n`);
    for (const f of result.deleted) process.stdout.write(`deleted ${f}\n`);
  }

  if (opts.ancestry) {
    const result = await writeAncestry(graph, opts.ancestry, opts.local);
    process.stdout.write(`wrote ${result.file}\n`);
  }

  if (opts.frontier) {
    const listing = renderFrontier(graph);
    if (opts.frontier === "-") {
      process.stdout.write(listing);
    } else {
      const filePath = resolve(opts.frontier);
      await mkdir(dirname(filePath), { recursive: true });
      await writeFile(filePath, listing);
      process.stdout.write(`wrote ${filePath}\n`);
    }
  }

  if (opts.alignment) {
    const alignmentTemplate = await readFile(resolve(HERE, "alignment-template.html"), "utf8");
    const alignmentHtml = buildAlignment(alignmentTemplate, graph);
    if (opts.alignment === "-") {
      process.stdout.write(alignmentHtml);
    } else {
      const filePath = resolve(opts.alignment);
      await mkdir(dirname(filePath), { recursive: true });
      await writeFile(filePath, alignmentHtml);
      process.stdout.write(`wrote ${filePath} (${Buffer.byteLength(alignmentHtml)} bytes)\n`);
    }
  }

  if (out) {
    for (const w of warnings) process.stderr.write(`contract: ${w}\n`);
    process.stdout.write(
      `${graph.nodes.length} nodes, ${Object.keys(graph.graphs).length} graphs -> ${out} (${Buffer.byteLength(html)} bytes)\n`
    );
  }

  if (!out && !opts.rules && !opts.ancestry && !opts.frontier && !opts.alignment) {
    process.stderr.write("nothing to do: pass --out, --rules, --ancestry (with --local), --frontier, or --alignment\n");
    process.exitCode = 1;
  }
}
